// belief_lens_config.js

export const beliefLenses = [
  {
    id: 'christian',
    name: 'The Living Word',
    description: 'A path of divine grace, scripture, and the indwelling Christ. Guided by the light of sacred text and the presence of Spirit.',
    tone: 'Reverent and devotional',
    icon: '📖',
    color: '#e4d0ba',
    overlays: ['scripture', 'holy-spirit', 'grace'],
    sampleAffirmation: 'I am held in the light of divine grace, a vessel of the Living Word.',
  },
  {
    id: 'jewish',
    name: 'The Covenant Flame',
    description: 'Rooted in sacred tradition, divine covenant, and the eternal spark. Illuminated by memory, mitzvot, and mystic flame.',
    tone: 'Poetic and ancestral',
    icon: '🕎',
    color: '#f9e0ae',
    overlays: ['covenant', 'light', 'tradition'],
    sampleAffirmation: 'The flame within me remembers. I walk in sacred covenant.',
  },
  {
    id: 'buddhist',
    name: 'The Middle Way',
    description: 'A balanced journey through presence, compassion, and detachment. Rooted in mindfulness and the nature of impermanence.',
    tone: 'Calm and centered',
    icon: '🧘',
    color: '#d0f0c0',
    overlays: ['emptiness', 'breath', 'compassion'],
    sampleAffirmation: 'With each breath, I return to the still point. I am enough.',
  },
  {
    id: 'muslim',
    name: 'The Path of Submission',
    description: 'A journey of devotion and trust in the One. Aligned to the rhythm of prayer and the beauty of surrender.',
    tone: 'Sacred and rhythmic',
    icon: '🕋',
    color: '#cde1f9',
    overlays: ['allah', 'surrender', 'unity'],
    sampleAffirmation: 'I surrender to divine will. In submission, I find peace.',
  },
  {
    id: 'metaphysical',
    name: 'The Sacred Science',
    description: 'An energetic path rooted in vibration, quantum alignment, and the unseen threads of consciousness.',
    tone: 'Expansive and intuitive',
    icon: '🔮',
    color: '#d4c0f7',
    overlays: ['energy', 'vibration', 'alignment'],
    sampleAffirmation: 'I am a frequency in the field. Aligned. Awakened. Expanding.',
  },
  {
    id: 'nonreligious',
    name: 'The Ever-Seeker',
    description: 'A reflective path for those walking in curiosity, reason, and open-hearted wonder — beyond systems, toward self-discovery.',
    tone: 'Grounded and poetic',
    icon: '🌿',
    color: '#e1e1e1',
    overlays: ['wonder', 'reason', 'presence'],
    sampleAffirmation: 'I follow the thread of truth wherever it leads. I am here to witness.',
  },
  {
    id: 'interfaith',
    name: 'The Eternal Weave',
    description: 'An integrative path that honors all traditions as threads in the same divine tapestry. Unity, harmony, and the One.',
    tone: 'Harmonic and unifying',
    icon: '🌀',
    color: '#fff2cc',
    overlays: ['unity', 'tapestry', 'oneness'],
    sampleAffirmation: 'I am all paths and no path. I weave light into wholeness.',
  }
];
